name: crime
version: 0.1.0
homepage: https://github.com/imvalient/crime
repository: https://github.com/imvalient/crime
description: >-
    Package to make requests to the Crime API crimeometer. It exposes four methods to gather
    information about crime stats and crime reports around the world.

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    http: ^0.13.1
    intl: ^0.17.0

dev_dependencies:
    test: ^1.16.8
    mockito: ^5.0.3
    build_runner: ^1.12.2